import { readFile, access } from "node:fs/promises";
import { dirname, join } from "node:path";
import vm from "node:vm";
const root = new URL("../", import.meta.url).pathname.replace(/^\/(.:)/,"$1");
const pages=["index.html","services.html","pricing.html","about.html","contact.html","privacy.html","terms.html"];
const expected={basic:60,standard:120,premium:160,annual:950,regular:120,deep:170,fullRefresh:200,fullDeep:270,key:10,contractor:25,callout:45,after:75,handyman:35,plumbing:40,electrical:45,hvac:45,inspection:60,postTenant:50,preArrival:40,damage:45,postDeparture:60,billsMin:25,billsMax:30,correspondence:15,coordination:35,handling:15,multiplier:1.5};
let failures=[];
const context={window:{}}; vm.createContext(context); vm.runInContext(await readFile(join(root,"js/config.js"),"utf8"),context); const c=context.window.JTC_CONFIG;
const actual={basic:c.plans.basic.priceMonthly,standard:c.plans.standard.priceMonthly,premium:c.plans.premium.priceMonthly,annual:c.annualPackage.priceYearly,regular:c.cleaning.regularRefresh.price,deep:c.cleaning.deepClean.price,fullRefresh:c.cleaning.fullRefresh.price,fullDeep:c.cleaning.fullDeepClean.price,key:c.access.keyHoldingMonthly,contractor:c.access.contractorAccess,callout:c.access.workingHoursCallout,after:c.access.afterHoursCallout,handyman:c.technical.handymanHourly,plumbing:c.technical.plumbingHourly,electrical:c.technical.electricalHourly,hvac:c.technical.hvacHourly,inspection:c.inspections.twoHourInspection,postTenant:c.inspections.postTenantFrom,preArrival:c.inspections.preArrivalFrom,damage:c.inspections.damageReportFrom,postDeparture:c.inspections.postDeparture,billsMin:c.administration.billHandlingMonthlyMinimum,billsMax:c.administration.billHandlingMonthlyMaximum,correspondence:c.administration.correspondencePerItem,coordination:c.administration.contractorCoordinationPerJob,handling:c.commercialTerms.contractorHandlingPercentage,multiplier:c.technical.emergencyMultiplier};
for(const [k,v] of Object.entries(expected)) if(actual[k]!==v) failures.push(`Pricing mismatch ${k}: ${actual[k]} (expected ${v})`);
for(const page of pages){ const file=join(root,page), html=await readFile(file,"utf8"); if(!html.includes('id="main"')) failures.push(`${page}: missing main landmark`); if(!html.includes("data-site-header")||!html.includes("data-site-footer")) failures.push(`${page}: missing shared header/footer hook`); if(/[—–]/.test(html)) failures.push(`${page}: long dash found; use a standard hyphen`); const publicPrices=[...html.matchAll(/€([0-9,]+)/g)].map(m=>Number(m[1].replace(",",""))); for(const value of publicPrices) if(![60,120,160].includes(value)) failures.push(`${page}: non-plan public price found: €${value}`); const attrs=[...html.matchAll(/(?:href|src)="([^"]+)"/g)].map(m=>m[1]).filter(x=>!x.startsWith("http")&&!x.startsWith("mailto:")&&!x.startsWith("tel:")&&!x.startsWith("#")&&!x.includes("?")); for(const rel of attrs){ const clean=rel.split("#")[0]; if(!clean) continue; try{await access(join(dirname(file),clean))}catch{failures.push(`${page}: broken local asset/link ${rel}`)} } }
for(const asset of ["assets/logo/jtc-property-services-logo.webp","assets/images/jtc-malta-property-hero.webp","assets/images/jtc-property-inspection.webp","assets/images/jtc-property-preparation.webp","css/styles.css","js/app.js"]) try{await access(join(root,asset))}catch{failures.push(`Missing required asset: ${asset}`)}
const home=await readFile(join(root,"index.html"),"utf8"); if((home.match(/data-slide/g)||[]).length<3) failures.push("Homepage slider must contain three property-care images.");
if(c.integrations.quoteEndpoint!=="") failures.push("Quote endpoint unexpectedly configured; live submissions require approval.");
if(failures.length){console.error(failures.join("\n"));process.exit(1)}
console.log(`PASS: ${pages.length} pages, required assets, local links, ${Object.keys(expected).length} commercial values, and integration safety checks.`);
